require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuditionsController do

  # This should return the minimal set of attributes required to create a valid
  # Audition. As you add validations to Audition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuditionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all auditions as @auditions" do
      audition = Audition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:auditions).should eq([audition])
    end
  end

  describe "GET show" do
    it "assigns the requested audition as @audition" do
      audition = Audition.create! valid_attributes
      get :show, {:id => audition.to_param}, valid_session
      assigns(:audition).should eq(audition)
    end
  end

  describe "GET new" do
    it "assigns a new audition as @audition" do
      get :new, {}, valid_session
      assigns(:audition).should be_a_new(Audition)
    end
  end

  describe "GET edit" do
    it "assigns the requested audition as @audition" do
      audition = Audition.create! valid_attributes
      get :edit, {:id => audition.to_param}, valid_session
      assigns(:audition).should eq(audition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Audition" do
        expect {
          post :create, {:audition => valid_attributes}, valid_session
        }.to change(Audition, :count).by(1)
      end

      it "assigns a newly created audition as @audition" do
        post :create, {:audition => valid_attributes}, valid_session
        assigns(:audition).should be_a(Audition)
        assigns(:audition).should be_persisted
      end

      it "redirects to the created audition" do
        post :create, {:audition => valid_attributes}, valid_session
        response.should redirect_to(Audition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved audition as @audition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Audition.any_instance.stub(:save).and_return(false)
        post :create, {:audition => {}}, valid_session
        assigns(:audition).should be_a_new(Audition)
      end

      # it "re-renders the 'new' template" do
      #   # Trigger the behavior that occurs when invalid params are submitted
      #   Audition.any_instance.stub(:save).and_return(false)
      #   post :create, {:audition => {}}, valid_session
      #   response.should render_template("new")
      # end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested audition" do
        audition = Audition.create! valid_attributes
        # Assuming there are no other auditions in the database, this
        # specifies that the Audition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Audition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => audition.to_param, :audition => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested audition as @audition" do
        audition = Audition.create! valid_attributes
        put :update, {:id => audition.to_param, :audition => valid_attributes}, valid_session
        assigns(:audition).should eq(audition)
      end

      it "redirects to the audition" do
        audition = Audition.create! valid_attributes
        put :update, {:id => audition.to_param, :audition => valid_attributes}, valid_session
        response.should redirect_to(audition)
      end
    end

    describe "with invalid params" do
      it "assigns the audition as @audition" do
        audition = Audition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Audition.any_instance.stub(:save).and_return(false)
        put :update, {:id => audition.to_param, :audition => {}}, valid_session
        assigns(:audition).should eq(audition)
      end

      # it "re-renders the 'edit' template" do
      #   audition = Audition.create! valid_attributes
      #   # Trigger the behavior that occurs when invalid params are submitted
      #   Audition.any_instance.stub(:save).and_return(false)
      #   put :update, {:id => audition.to_param, :audition => {}}, valid_session
      #   response.should render_template("edit")
      # end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested audition" do
      audition = Audition.create! valid_attributes
      expect {
        delete :destroy, {:id => audition.to_param}, valid_session
      }.to change(Audition, :count).by(-1)
    end

    it "redirects to the auditions list" do
      audition = Audition.create! valid_attributes
      delete :destroy, {:id => audition.to_param}, valid_session
      response.should redirect_to(auditions_url)
    end
  end

end
